"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const disableNavbar = ["/login", "/404"];
const disableFooter = ["/login", "/404"];

export const metadata: Metadata = {
  title: "Top up voucher game | ARDINAL YUSRA",
  description: "Generated by Ardinal Yusra",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        {!disableNavbar.includes(pathname) && <Navbar />}
        {children}
        {!disableFooter.includes(pathname) && <Footer />}
      </body>
    </html>
  );
}
